var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/client/[client_code]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__ca148056._.js")
R.c("server/chunks/ssr/client-health-dashboard_app_d5df67c8._.js")
R.c("server/chunks/ssr/client-health-dashboard_app_79b39296._.js")
R.c("server/chunks/ssr/[root-of-the-server]__953e96f2._.js")
R.c("server/chunks/ssr/0684f_932f2286._.js")
R.c("server/chunks/ssr/0684f_next_dist_4bf00ea1._.js")
R.c("server/chunks/ssr/client-health-dashboard_app_src_app_f4f9c4fd._.js")
R.c("server/chunks/ssr/client-health-dashboard_app_src_app_2ba87250._.js")
R.c("server/chunks/ssr/0684f_next_dist_client_components_builtin_global-error_32bcf417.js")
R.c("server/chunks/ssr/[root-of-the-server]__634c3fda._.js")
R.c("server/chunks/ssr/0684f_next_dist_client_components_7bfb78f4._.js")
R.c("server/chunks/ssr/0684f_next_dist_client_components_builtin_forbidden_8663e7e0.js")
R.c("server/chunks/ssr/0684f_next_dist_client_components_builtin_unauthorized_6ead38aa.js")
R.c("server/chunks/ssr/e1fbd_app__next-internal_server_app_client_[client_code]_page_actions_3f28f02e.js")
R.m(66261)
module.exports=R.m(66261).exports
